Asp.NetStudentManagementSystem/Models/Group.cs
namespace Asp.NetStudentManagementSystem.Models
{
    public class Group
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Department? Department { get; set; }
        public int DepartmentId { get; set; }
        public ICollection<UsersInfo>? Students { get; set; }
        public ICollection<GroupSubject>? GroupSubjects { get; set; }
        public ICollection<Exam>? Exams { get; set; }
    }
}

Asp.NetStudentManagementSystem/Areas/Admin/Controllers/GroupController.cs
using Asp.NetStudentManagementSystem.DAL;
using Asp.NetStudentManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Asp.NetStudentManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class GroupController : Controller
    {
        UserManager<AppUser> _userManager { get; }
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public GroupController(AppDbContext context, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var groups = _context.Groups.Include(x=>x.Department);
            return View(groups);
        }

        public IActionResult Create()
        {
            ViewBag.Departments = _context.Departments.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Group group)
        {
            if (!ModelState.IsValid) return View();
            _context.Groups.Add(group);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            ViewBag.Departments = _context.Departments.ToList();
            var group = _context.Groups.Find(id);
            return View(group);
        }


        [HttpPost]
        public IActionResult Update(int? id, Group group)
        {
            ViewBag.Departments = _context.Departments.ToList();
            if (id != group.Id || id is null) return BadRequest();
            if (!ModelState.IsValid) return View(group);
            var editGroup = _context.Groups.Find(id);
            if (editGroup is null) return BadRequest();
            editGroup.Name = group.Name;
            editGroup.DepartmentId = group.DepartmentId;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

Asp.NetStudentManagementSystem/Areas/Admin/Views/Group/Create.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Qrup yarat";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Group
<table class="subjects-table table table-striped table-bordered">
</table>
<div class="container d-flex justify-content-center p-3">
    <form class="col-6" method="post" asp-controller="Group" asp-action="Create">
        <label asp-for="Name">Ad</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>

        <div class="form-input-control mt-2 mb-3">
            <select asp-for="DepartmentId" class="gender-selection w-100 form-control">
                 <option value="">-- Aid olduğu şöbəni seçin --</option>
                @foreach (var item in (ViewBag.Departments as List<Department>))
                {
                <option value="@item.Id">@item.Name</option>
                }
            </select>
        </div>

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <button type="submit" class="btn btn-primary" style="background-color:#144365;border:none">Yarat</button>
    </form>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
}

Asp.NetStudentManagementSystem/Areas/Admin/Views/Group/Index.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Qruplar";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Group>
<table class="subjects-table table table-striped table-bordered">
</table>

<a class="admin-buttons" asp-controller="Group" asp-action="Create">Yeni qrup yarat</a>
<table style="table-layout:auto" class="table table-responsive table-striped table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Ad</th>
            <th>Aid olduğu şöbə</th>
            <th>Düzəliş et</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Department.Name</td>
                <td><a class="admin-buttons" asp-controller="Group" asp-action="Update" asp-route-id="@item.Id">Düzəliş et</a></td>
            </tr>
        }
    </tbody>
</table>

Asp.NetStudentManagementSystem/Areas/Admin/Views/Group/Update.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Düzəliş et";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Group
<table class="subjects-table table table-striped table-bordered">
</table>
<div class="container d-flex justify-content-center p-3">
    <form class="col-6" method="post" asp-controller="Group" asp-action="Update">
        <label asp-for="Name">Ad</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>

        <div class="form-input-control mt-2 mb-3">
            <select asp-for="DepartmentId" class="gender-selection w-100 form-control">
                 <option value="">-- Aid olduğu şöbəni seçin --</option>
                @foreach (var item in (ViewBag.Departments as List<Department>))
                {
                <option value="@item.Id">@item.Name</option>
                }
            </select>
        </div>

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <button type="submit" class="btn btn-primary" style="background-color:#144365;border:none">Düzəliş et</button>
    </form>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
}