Asp.NetStudentManagementSystem/Models/Schedule.cs
namespace Asp.NetStudentManagementSystem.Models
{
    public class Schedule
    {
        public int Id { get; set; }
        public LessonHour? LessonHour { get; set; }
        public int LessonHourId { get; set; }
        public LessonDay? LessonDay { get; set; }
        public int LessonDayId { get; set; }
        public int Room { get; set; }
        public Group? Group { get; set; }
        public int GroupId { get; set; }
        public Subject? Subject { get; set; }
        public int SubjectId { get; set; }
        public bool isDeleted { get; set; }

    }
}

Asp.NetStudentManagementSystem/Areas/Admin/Controllers/ScheduleController.cs
using Asp.NetStudentManagementSystem.DAL;
using Asp.NetStudentManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Asp.NetStudentManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class ScheduleController : Controller
    {
        UserManager<AppUser> _userManager { get; }
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ScheduleController(AppDbContext context, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var schedules = _context.Schedules.Include(x => x.LessonHour).Include(x => x.LessonDay).Include(x => x.Group).Include(x => x.Subject);
            return View(schedules);
        }
        public IActionResult Create()
        {
            ViewBag.Time = _context.LessonHours.ToList();
            ViewBag.Days = _context.LessonDays.ToList();
            ViewBag.Subjects = _context.Subjects.ToList();
            ViewBag.Groups = _context.Groups.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Schedule schedule)
        {
            if (!ModelState.IsValid) return View();
            _context.Schedules.Add(schedule);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            ViewBag.Time = _context.LessonHours.ToList();
            ViewBag.Days = _context.LessonDays.ToList();
            ViewBag.Subjects = _context.Subjects.ToList();
            ViewBag.Groups = _context.Groups.ToList();

            var schedule = _context.Schedules.Find(id);
            return View(schedule);
        }

        [HttpPost]
        public IActionResult Update(int? id, Schedule schedule)
        {
            ViewBag.Time = _context.LessonHours.ToList();
            ViewBag.Days = _context.LessonDays.ToList();
            ViewBag.Subjects = _context.Subjects.ToList();
            ViewBag.Groups = _context.Groups.ToList();
            if (id != schedule.Id || id is null) return BadRequest();
            if (!ModelState.IsValid) return View(schedule);
            var editSchedule = _context.Schedules.Find(id);
            if (editSchedule is null) return BadRequest();
            editSchedule.Room = schedule.Room;
            editSchedule.LessonDayId = schedule.LessonDayId;
            editSchedule.LessonHourId = schedule.LessonHourId;
            editSchedule.SubjectId = schedule.SubjectId;
            editSchedule.GroupId = schedule.GroupId;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Asp.NetStudentManagementSystem/Areas/Admin/Views/Schedule/Create.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Cədvəl yarat";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Schedule
<table class="subjects-table table table-striped table-bordered">
</table>
<div class="container d-flex justify-content-center p-3">
    <form class="col-6" method="post" asp-controller="Schedule" asp-action="Create">
        <label asp-for="Room">Otaq</label>
        <input class="form-control" type="number" asp-for="Room" />
        <span class="text-danger" asp-validation-for="Room"></span>

        <div class="form-input-control mt-2">
            <select asp-for="LessonHourId" class="gender-selection w-100 form-control">
                <option value="">-- Saatı seçin --</option>
                @foreach (var item in (ViewBag.Time as List<LessonHour>))
                {
                    <option value="@item.Id">@item.Begin - @item.End</option>
                }
            </select>
        </div>

        <div class="form-input-control mt-2">
            <select asp-for="LessonDayId" class="gender-selection w-100 form-control">
                <option value="">-- Günü seçin --</option>
                @foreach (var item in (ViewBag.Days as List<LessonDay>))
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
        </div>

        <div class="form-input-control mt-2">
            <select asp-for="SubjectId" class="gender-selection w-100 form-control">
                <option value="">-- Fənni seçin --</option>
                @foreach (var item in (ViewBag.Subjects as List<Subject>))
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
        </div>
        <div class="form-input-control mt-2 mb-3">
            <select asp-for="GroupId" class="gender-selection w-100 form-control">
                <option value="">-- Qrupu seçin --</option>
                @foreach (var item in (ViewBag.Groups as List<Group>))
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
        </div>

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <button type="submit" class="btn btn-primary" style="background-color:#144365;border:none">Yarat</button>
    </form>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
}

Asp.NetStudentManagementSystem/Areas/Admin/Views/Schedule/Index.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Cədvəllər";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Schedule>
 <table class="subjects-table table table-striped table-bordered">
     </table>

     <a class="admin-buttons" asp-controller="Schedule" asp-action="Create">Yeni cədvəl yarat</a>
    <table style="table-layout:auto" class="table table-responsive table-striped table-bordered">
         <thead>
             <tr>
                <th>Id</th>
                <th>Otaq</th>
                <th>Saat</th>
                <th>Gün</th>
                <th>Qrup</th>
                <th>Dərs</th>
                <th>Düzəliş et</th>
        </tr>
         </thead>
         <tbody>
             @foreach (var item in Model)
             {
                 <tr>
                     <td>@item.Id</td>
                     <td>@item.Room</td>
                     <td>@item.LessonHour.Begin - @item.LessonHour.End</td>
                     <td>@item.LessonDay.Name</td>
                     <td>@item.Group.Name</td>
                     <td>@item.Subject.Name</td>
                     <td><a class="admin-buttons" asp-controller="Schedule" asp-action="Update" asp-route-id="@item.Id">Düzəliş et</a></td>
                 </tr>
             }
          </tbody>
    </table>

Asp.NetStudentManagementSystem/Areas/Admin/Views/Schedule/Update.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Düzəliş et";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Schedule
<table class="subjects-table table table-striped table-bordered">
</table>
<div class="container d-flex justify-content-center p-3">
    <form class="col-6" method="post" asp-controller="Schedule" asp-action="Update">
        <label asp-for="Room">Otaq</label>
        <input class="form-control" type="number" asp-for="Room" />
        <span class="text-danger" asp-validation-for="Room"></span>

        <div class="form-input-control mt-2">
            <select asp-for="LessonHourId" class="gender-selection w-100 form-control">
                <option value="">-- Saatı seçin --</option>
                @foreach (var item in (ViewBag.Time as List<LessonHour>))
                {
                    <option value="@item.Id">@item.Begin - @item.End</option>
                }
            </select>
        </div>

        <div class="form-input-control mt-2">
            <select asp-for="LessonDayId" class="gender-selection w-100 form-control">
                <option value="">-- Günü seçin --</option>
                @foreach (var item in (ViewBag.Days as List<LessonDay>))
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
        </div>

        <div class="form-input-control mt-2">
            <select asp-for="SubjectId" class="gender-selection w-100 form-control">
                <option value="">-- Fənni seçin --</option>
                @foreach (var item in (ViewBag.Subjects as List<Subject>))
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
        </div>
        <div class="form-input-control mt-2 mb-3">
            <select asp-for="GroupId" class="gender-selection w-100 form-control">
                <option value="">-- Qrupu seçin --</option>
                @foreach (var item in (ViewBag.Groups as List<Group>))
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
        </div>

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <button type="submit" class="btn btn-primary" style="background-color:#144365;border:none">Yarat</button>
    </form>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
}