Asp.NetStudentManagementSystem/Models/Notification.cs
namespace Asp.NetStudentManagementSystem.Models
{
    public class Notification
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime DateTime { get; set; }
        public string Content { get; set; }
    }
}

Asp.NetStudentManagementSystem/Areas/Admin/Controllers/NotificationController.cs
using Asp.NetStudentManagementSystem.DAL;
using Asp.NetStudentManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Asp.NetStudentManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class NotificationController : Controller
    {

        UserManager<AppUser> _userManager { get; }
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public NotificationController(AppDbContext context, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var notifications = _context.Notifications;
            return View(notifications);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Notification notification)
        {
            if (!ModelState.IsValid) return View();
            notification.DateTime = DateTime.Now;
            _context.Notifications.Add(notification);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            var notification = _context.Notifications.Find(id);
            return View(notification);
        }

        [HttpPost]
        public IActionResult Update(int? id, Notification notification)
        {
            if (id != notification.Id || id is null) return BadRequest();
            if (!ModelState.IsValid) return View(notification);
            var editNot = _context.Notifications.Find(id);
            if (editNot is null) return BadRequest();
            editNot.Title = notification.Title;
            editNot.Content = notification.Content;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Asp.NetStudentManagementSystem/Areas/Admin/Views/Notification/Create.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Bildiriş yarat";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Notification
<table class="subjects-table table table-striped table-bordered">
</table>
<div class="container d-flex justify-content-center">
    <form class="col-6" method="post" asp-controller="Notification" asp-action="Create">
        <label asp-for="Title">Bildirişin başlığı</label>
        <input class="form-control" asp-for="Title" /> <br />
        <span class="text-danger" asp-validation-for="Title"></span>


        <label asp-for="Content">Məzmun</label>
        <input class="form-control" asp-for="Content" /> <br />
        <span class="text-danger" asp-validation-for="Content"></span>

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <button type="submit" class="btn btn-primary" style="background-color:#144365;border:none">Yarat</button>
    </form>
</div>

@section scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js" integrity="sha512-rstIgDs0xPgmG6RX1Aba4KV5cWJbAMcvRCVmglpam9SoHZiUCyQVDdH2LPlxoHtrv17XWblE/V/PP+Tr04hbtA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
}

Asp.NetStudentManagementSystem/Areas/Admin/Views/Notification/Index.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Bildirişlər";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<Notification>
 <table class="subjects-table table table-striped table-bordered">
     </table>

    <a class="admin-buttons" asp-controller="Notification" asp-action="Create">Yeni bildiriş yarat</a>
    <table style="table-layout:auto" class="students-table table table-responsive table-striped table-bordered">
         <thead>
             <tr>
                <th>Id</th>
                <th>Başlıq</th>
                <th>Yaradılma tarixi</th>
                <th>Məzmun</th>
                <th>Düzəliş et</th>
        </tr>
         </thead>
         <tbody>
             @foreach (var item in Model)
             {
                 <tr>
                     <td>@item.Id</td>
                     <td>@item.Title</td>
                     <td>@item.DateTime.ToShortDateString()</td>
                     <td>@item.Content</td>
                      <td> <a class="admin-buttons" asp-controller="Notification" asp-action="Update" asp-route-id="@item.Id">Düzəliş et</a></td>
                 </tr>
             }
          </tbody>
    </table>

Asp.NetStudentManagementSystem/Areas/Admin/Views/Notification/Update.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Düzəliş et";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Notification
<table class="subjects-table table table-striped table-bordered">
</table>
<div class="container d-flex justify-content-center">
    <form class="col-6" method="post" asp-controller="Notification" asp-action="Update">
        <label asp-for="Title">Bildirişin başlığı</label>
        <input class="form-control" asp-for="Title" /> <br />
        <span class="text-danger" asp-validation-for="Title"></span>


        <label asp-for="Content">Məzmun</label>
        <input class="form-control" asp-for="Content" /> <br />
        <span class="text-danger" asp-validation-for="Content"></span>

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <button type="submit" class="btn btn-primary" style="background-color:#144365;border:none">Təsdiqlə</button>
    </form>
</div>