Asp.NetStudentManagementSystem/Models/Exam.cs
namespace Asp.NetStudentManagementSystem.Models
{
    public class Exam
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public Group? Group { get; set; }
        public int GroupId { get; set; }
        public Subject? Subject { get; set; }
        public int SubjectId { get; set; }
        public bool isDeleted { get; set; }
    }
}

Asp.NetStudentManagementSystem/Models/Schedule.cs
namespace Asp.NetStudentManagementSystem.Models
{
    public class Schedule
    {
        public int Id { get; set; }
        public LessonHour? LessonHour { get; set; }
        public int LessonHourId { get; set; }
        public LessonDay? LessonDay { get; set; }
        public int LessonDayId { get; set; }
        public int Room { get; set; }
        public Group? Group { get; set; }
        public int GroupId { get; set; }
        public Subject? Subject { get; set; }
        public int SubjectId { get; set; }
        public bool isDeleted { get; set; }

    }
}

Asp.NetStudentManagementSystem/Areas/Admin/Controllers/AppealController.cs
using Asp.NetStudentManagementSystem.DAL;
using Asp.NetStudentManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Asp.NetStudentManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class AppealController : Controller
    {
        UserManager<AppUser> _userManager { get; }
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AppealController(AppDbContext context, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var appeals = _context.StudentAppeals.Include(x => x.AppUser).Include(x => x.Subject);
            return View(appeals);
        }

        public IActionResult Update(int id)
        {
            var studentAppeal = _context.StudentAppeals.Include(x=>x.AppUser).Include(x => x.Subject).FirstOrDefault(x=>x.Id == id);
            return View(studentAppeal);
        }


        [HttpPost]
        public IActionResult Update(int? id, StudentAppeal appeal )
        {
            if (id != appeal.Id || id is null) return BadRequest();
            if (!ModelState.IsValid) return View(appeal);
            var editAppeal = _context.StudentAppeals.Find(id);
            if (editAppeal is null) return BadRequest();
            editAppeal.IsAllowed = appeal.IsAllowed;
            editAppeal.IsActive = appeal.IsActive;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

Asp.NetStudentManagementSystem/Areas/Admin/Controllers/ExamController.cs
using Asp.NetStudentManagementSystem.DAL;
using Asp.NetStudentManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Asp.NetStudentManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class ExamController : Controller
    {
        UserManager<AppUser> _userManager { get; }
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ExamController(AppDbContext context, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var exams = _context.Exams.Include(x=>x.Group).Include(x => x.Subject);
            return View(exams);
        }

        public IActionResult Create()
        {
            ViewBag.Groups = _context.Groups.ToList();
            ViewBag.Subjects = _context.Subjects.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Exam exam)
        {
            if (!ModelState.IsValid) return View();
            _context.Exams.Add(exam);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            ViewBag.Groups = _context.Groups.ToList();
            ViewBag.Subjects = _context.Subjects.ToList();
            var exam = _context.Exams.Find(id);
            return View(exam);
        }

        [HttpPost]
        public IActionResult Update(int? id, Exam exam)
        {
            ViewBag.Groups = _context.Groups.ToList();
            ViewBag.Subjects = _context.Subjects.ToList();
            if (id != exam.Id || id is null) return BadRequest();
            if (!ModelState.IsValid) return View(exam);
            var editExam = _context.Exams.Find(id);
            if (editExam is null) return BadRequest();
            editExam.Date = exam.Date;
            editExam.SubjectId = exam.SubjectId;
            editExam.GroupId = exam.GroupId;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Asp.NetStudentManagementSystem/Areas/Admin/Controllers/ScheduleController.cs
using Asp.NetStudentManagementSystem.DAL;
using Asp.NetStudentManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Asp.NetStudentManagementSystem.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "SuperAdmin")]
    public class ScheduleController : Controller
    {
        UserManager<AppUser> _userManager { get; }
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ScheduleController(AppDbContext context, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var schedules = _context.Schedules.Include(x => x.LessonHour).Include(x => x.LessonDay).Include(x => x.Group).Include(x => x.Subject);
            return View(schedules);
        }
        public IActionResult Create()
        {
            ViewBag.Time = _context.LessonHours.ToList();
            ViewBag.Days = _context.LessonDays.ToList();
            ViewBag.Subjects = _context.Subjects.ToList();
            ViewBag.Groups = _context.Groups.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Schedule schedule)
        {
            if (!ModelState.IsValid) return View();
            _context.Schedules.Add(schedule);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int id)
        {
            ViewBag.Time = _context.LessonHours.ToList();
            ViewBag.Days = _context.LessonDays.ToList();
            ViewBag.Subjects = _context.Subjects.ToList();
            ViewBag.Groups = _context.Groups.ToList();

            var schedule = _context.Schedules.Find(id);
            return View(schedule);
        }

        [HttpPost]
        public IActionResult Update(int? id, Schedule schedule)
        {
            ViewBag.Time = _context.LessonHours.ToList();
            ViewBag.Days = _context.LessonDays.ToList();
            ViewBag.Subjects = _context.Subjects.ToList();
            ViewBag.Groups = _context.Groups.ToList();
            if (id != schedule.Id || id is null) return BadRequest();
            if (!ModelState.IsValid) return View(schedule);
            var editSchedule = _context.Schedules.Find(id);
            if (editSchedule is null) return BadRequest();
            editSchedule.Room = schedule.Room;
            editSchedule.LessonDayId = schedule.LessonDayId;
            editSchedule.LessonHourId = schedule.LessonHourId;
            editSchedule.SubjectId = schedule.SubjectId;
            editSchedule.GroupId = schedule.GroupId;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Asp.NetStudentManagementSystem/Controllers/StudentJournalController.cs
using Asp.NetStudentManagementSystem.DAL;
using Asp.NetStudentManagementSystem.Models;
using Asp.NetStudentManagementSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Asp.NetStudentManagementSystem.Controllers
{
    [Authorize(Roles="Member")]
    public class StudentJournalController : Controller
    {
        UserManager<AppUser> _userManager { get; }
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public StudentJournalController(AppDbContext context, UserManager<AppUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _userManager = userManager;
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index(int? id)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var currentStudent = _context.UserInfos.FirstOrDefault(x => x.Email == currentUser.Email);
            StudentJournalVM vm = new StudentJournalVM();
            vm.GroupSubjects = _context.GroupSubjects.Include(x => x.Subject).Where(x => x.GroupId == currentStudent.GroupId);
            if (id is null)
            {
                return View(vm);
            }
            vm.Attendances = _context.Attendances.Include(x => x.Student).Where(x => x.SubjectId == id && x.StudentId == currentStudent.Id);
            return View(vm);
        }

        public async Task<IActionResult> Exam()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var currentStudent = _context.UserInfos.FirstOrDefault(x => x.Email == currentUser.Email);
            var exam = _context.Exams.Include(x => x.Subject).Include(x => x.Group).Where(x => x.GroupId == currentStudent.GroupId && x.isDeleted == false);
            return View(exam);
        }

        public async Task<IActionResult> Schedule()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var currentStudent = _context.UserInfos.FirstOrDefault(x => x.Email == currentUser.Email);
            var exam = _context.Schedules.Include(x => x.Subject)
                .Include(x => x.Group)
                .Include(x => x.LessonDay)
                .Include(x => x.LessonHour)
                .Where(x => x.GroupId == currentStudent.GroupId && x.isDeleted == false);
            return View(exam);
        }

        public async Task<IActionResult> Appeal()
        {
            var currentStudent = await _userManager.GetUserAsync(User);
            var studentAppeals = _context.StudentAppeals.Include(x => x.AppUser).Include(x => x.Subject).Where(x=> x.AppUserId == currentStudent.Id && x.IsAllowed == true);
            return View(studentAppeals);
        }

        public async Task<IActionResult> AppealCreate()
        {
            ViewBag.IsSent = false;
            ViewBag.Subjects = _context.Subjects.ToList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AppealCreate(StudentAppeal appeal)
        {

            ViewBag.Subjects = _context.Subjects.ToList();
            var currentUser = await _userManager.GetUserAsync(User);

            appeal.Date = DateTime.Now;
            appeal.AppUserId = currentUser.Id;
            appeal.IsActive = true;
            appeal.IsAllowed = false;
            if (!ModelState.IsValid) return View();
            ViewBag.IsSent = true;

            _context.StudentAppeals.Add(appeal);
            _context.SaveChanges();
            return View();
        }
    }
}

Asp.NetStudentManagementSystem/Views/StudentJournal/Appeal.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Appelyasiya";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model IEnumerable<StudentAppeal>

<table class="subjects-table table table-striped table-bordered">
</table>

<a class="admin-buttons" asp-controller="StudentJournal" asp-action="AppealCreate">Müraciət et</a>
<table style="table-layout:auto" class="table table-responsive table-striped table-bordered">
    <thead>
        <tr>
            <th>Fənn</th>
            <th>Şikayətin tarixi</th>
            <th>Şikayətin məzmunu</th>
            <th>Şikayətin statusu</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() == 0)
        {
            <tr> <td colspan="4" class="text-center">Nəticə yoxdur </td> </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.Subject.Name</td>
                    <td>@item.Date.ToShortDateString()</td>
                    <td>@item.Content</td>
                    @if (item.IsActive)
                    {
                        <td class="text-success" style="font-weight:bold">Aktiv</td>
                    }
                    else
                    {
                        <td class="text-danger" style="font-weight:bold">Deaktiv</td>
                    }
                </tr>
            }
        }
    </tbody>
</table>

Asp.NetStudentManagementSystem/Views/StudentJournal/AppealCreate.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Appealyasiya Müraciət";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model StudentAppeal
<table class="subjects-table table table-striped table-bordered">
</table>

<div class="container d-flex justify-content-center">
    @if (ViewBag.IsSent == true)
    {
        <div class="d-flex justify-content-center">
            <div class="alert alert-success text-center" style="height:60px;width:50vw" role="alert">
                <span class="text-dark">Sizin appelyasiya müraciətiniz qəbul olunmuşdur.</span>
            </div>
        </div>
    }
    else
    {
       
    <form class="col-6" method="post" asp-controller="StudentJournal" asp-action="AppealCreate">

        <label asp-for="Content">Məzmun</label>
        <input class="form-control" asp-for="Content" /> <br />
        <span class="text-danger" asp-validation-for="Content"></span>

        <div class="form-input-control">
            <select asp-for="SubjectId" class="gender-selection w-100 form-control">
                <option value="">-- Fənni seçin --</option>
                @foreach (var item in (ViewBag.Subjects as List<Subject>))
                {
                    <option value="@item.Id">@item.Name</option>
                }
            </select>
            <span class="text-danger" asp-validation-for="SubjectId"></span>
        </div>

        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <button type="submit" class="admin-buttons mt-3">Yarat</button>
    </form>
    }
</div>

Asp.NetStudentManagementSystem/Views/StudentJournal/Exam.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "İmtahanlar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Exam>

    @if (Model is null)
    {
         <table class="subjects-table table table-striped table-bordered">
         <thead>
             <tr>
                 <th class="text-center">Imtahan Tarixi</th>
                 <th class="text-center">Qrup</th>
                <th class="text-center">Imtahan Fənni</th>
            </tr>
         </thead>
          <tbody>
              <tr>
                  <td colspan="3">Imtahan nəzərdə tutulmayıb</td>
              </tr>
         </tbody>
        </table>
    }
    else
    {
    
        <table class="subjects-table table table-striped table-bordered">
         <thead>
             <tr>
                 <th class="text-center">Imtahan Tarixi</th>
                 <th class="text-center">Qrup</th>
                <th class="text-center">Imtahan Fənni</th>
            </tr>
         </thead>
          <tbody>
             @foreach (var item in Model)
             {
                 <tr>
                     <td align="center" style="display:flex;flex-direction:column">
                           <span>@item.Date.ToShortDateString()</span>
                          <span>Başlama-bitmə : @item.Date.ToShortTimeString() - @item.Date.AddHours(3).ToShortTimeString()</span>
                     </td>
                     <td align="center">@item.Group.Name</td>
                     <td align="center">@item.Subject.Name</td>
                </tr>
             }
         </tbody>
</table>
    }

Asp.NetStudentManagementSystem/Views/StudentJournal/Index.cshtml
@using Asp.NetStudentManagementSystem.ViewModels

@{
    ViewData["Title"] = "Jurnal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model StudentJournalVM


<div class="dropdown">
  <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Dərsi seçin
  </button>
  <ul class="dropdown-menu">
      @foreach (var item in Model.GroupSubjects)
      {
        <li><a class="dropdown-item" asp-route-id="@item.Id">@item.Subject.Name</a></li>
      }
  </ul>
</div>

<table class="subjects-table table table-striped table-bordered">
    <thead>
        <tr>
            <th>Tarix</th>
            <th>Dərs</th>
            <th>Tələbə</th>
            <th>Qiymət</th>
            <th>İştirak</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            @if (Model.Attendances is null)
            {
                <tr><td align="center" colspan="5">Nəticə yoxdur</td></tr>
            }
            else
            {
            foreach (var item in Model.Attendances)
            {
                <tr>
                    <td>@item.Date.ToShortDateString()</td>
                    <td>@item.Subject.Name</td>
                    <td>@item.Student.Name @item.Student.Surname</td>
                    @if (@item.Grade is null)
                    {
                     <td>Qiymətsiz</td>
                    }
                    else
                    {
                    <td>@item.Grade</td>  
                    }
                    @if (item.IsPresent == true)
                    {
                    <td>i/e</td>
                    }
                    else
                    {
                    <td>q/b</td>
                    }
                    
                </tr>
            }
            }
        </tr>
    </tbody>
</table>

Asp.NetStudentManagementSystem/Views/StudentJournal/Schedule.cshtml
@using Asp.NetStudentManagementSystem.Models

@{
    ViewData["Title"] = "Cədvəl";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Schedule>
@*    @if (Model is null)
    {
         <table class="subjects-table table table-striped table-bordered">
         <thead>
             <tr>
                 <th class="text-center">Gün</th>
                <th class="text-center">Fənn</th>
            </tr>
         </thead>
          <tbody>
              <tr>
                  <td colspan="3">Imtahan nəzərdə tutulmayıb</td>
              </tr>
         </tbody>
        </table>
    }
    else
    {

        <table class="subjects-table table table-striped table-bordered">
         <thead>
             <tr>
                 <th class="text-center">Gün</th>
                <th class="text-center">Fənn</th>
            </tr>
         </thead>
          <tbody>
             @foreach (var item in Model)
             {
                 <tr>
                     <td>@item.LessonDay.Name</td>
                     <td align="center" style="display:flex;flex-direction:column">
                           <span>@item.Subject.Name</span>
                           <span>@item.Room</span>
                          <span>Başlama-bitmə : @item.LessonHour.Begin - @item.LessonHour.End</span>
                     </td>
                </tr>
             }
         </tbody>
</table>
    }*@

<table class="subjects-table table table-striped table-bordered text-center">
    <thead>
        <tr>
            <th>Saat</th>
            <th>Bazar ertəsi</th>
            <th>Çərşənbə axşamı</th>
            <th>Çərşənbə</th>
            <th>Cümə axşamı</th>
            <th>Cümə</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th class="text-center">08:30-09:50</th>
            <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 1 && x.LessonDay.Id == 1) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 1 && x.LessonDay.Id == 1);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br /> 
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
            <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 1 && x.LessonDay.Id == 2) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 1 && x.LessonDay.Id == 2);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br /> 
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
            <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 1 && x.LessonDay.Id == 3) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 1 && x.LessonDay.Id == 3);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br /> 
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
             <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 1 && x.LessonDay.Id == 4) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 1 && x.LessonDay.Id == 4);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br /> 
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
             <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 1 && x.LessonDay.Id == 5) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 1 && x.LessonDay.Id == 5);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br /> 
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
        </tr>
        <tr>
            <th class="text-center">10:00-11:20</th>
             <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 2 && x.LessonDay.Id == 1) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 2 && x.LessonDay.Id == 1);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br /> 
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
             <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 2 && x.LessonDay.Id == 2) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 2 && x.LessonDay.Id == 2);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br /> 
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
             <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 2 && x.LessonDay.Id == 3) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 2 && x.LessonDay.Id == 3);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br />  
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
             <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 2 && x.LessonDay.Id == 4) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 2 && x.LessonDay.Id == 4);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br /> 
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
             <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 2 && x.LessonDay.Id == 5) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 2 && x.LessonDay.Id == 5);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br /> 
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
        </tr>
        <tr>
            <th class="text-center">11:30-12:50</th>
            <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 3 && x.LessonDay.Id == 1) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 3 && x.LessonDay.Id == 1);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br />  
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
            <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 3 && x.LessonDay.Id == 2) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 3 && x.LessonDay.Id == 2);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br />  
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
            <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 3 && x.LessonDay.Id == 3) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 3 && x.LessonDay.Id == 3);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br />  
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
            <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 3 && x.LessonDay.Id == 4) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 3 && x.LessonDay.Id == 4);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br />  
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
            <td>
                @if (Model.FirstOrDefault(x=>x.LessonHour.Id == 3 && x.LessonDay.Id == 5) != null)
                {
                    var info = Model.FirstOrDefault(x => x.LessonHour.Id == 3 && x.LessonDay.Id == 5);
                    <span>@info.Subject.Name</span> <br />
                    <span>Otaq(@info.Room)</span> <br />  
                }
                else
                {
                    <span>Boş</span>
                }
            </td>
        </tr>
    </tbody>
</table>